# Python stubs generated by omniidl from idl/SpeechManage.idl

import omniORB, _omnipy
from omniORB import CORBA, PortableServer
_0_CORBA = CORBA

_omnipy.checkVersion(3,0, __file__)


#
# Start of module "Manage"
#
__name__ = "Manage"
_0_Manage = omniORB.openModule("Manage", r"idl/SpeechManage.idl")
_0_Manage__POA = omniORB.openModule("Manage__POA", r"idl/SpeechManage.idl")


# typedef ... StringList
class StringList:
    _NP_RepositoryId = "IDL:Manage/StringList:1.0"
    def __init__(self, *args, **kw):
        raise RuntimeError("Cannot construct objects of this type.")
_0_Manage.StringList = StringList
_0_Manage._d_StringList  = (omniORB.tcInternal.tv_sequence, (omniORB.tcInternal.tv_string,0), 0)
_0_Manage._ad_StringList = (omniORB.tcInternal.tv_alias, StringList._NP_RepositoryId, "StringList", (omniORB.tcInternal.tv_sequence, (omniORB.tcInternal.tv_string,0), 0))
_0_Manage._tc_StringList = omniORB.tcInternal.createTypeCode(_0_Manage._ad_StringList)
omniORB.registerType(StringList._NP_RepositoryId, _0_Manage._ad_StringList, _0_Manage._tc_StringList)
del StringList

# interface SpeechManage
_0_Manage._d_SpeechManage = (omniORB.tcInternal.tv_objref, "IDL:Manage/SpeechManage:1.0", "SpeechManage")
omniORB.typeMapping["IDL:Manage/SpeechManage:1.0"] = _0_Manage._d_SpeechManage
_0_Manage.SpeechManage = omniORB.newEmptyClass()
class SpeechManage :
    _NP_RepositoryId = _0_Manage._d_SpeechManage[1]

    def __init__(self, *args, **kw):
        raise RuntimeError("Cannot construct objects of this type.")

    _nil = CORBA.Object._nil


_0_Manage.SpeechManage = SpeechManage
_0_Manage._tc_SpeechManage = omniORB.tcInternal.createTypeCode(_0_Manage._d_SpeechManage)
omniORB.registerType(SpeechManage._NP_RepositoryId, _0_Manage._d_SpeechManage, _0_Manage._tc_SpeechManage)

# SpeechManage operations and attributes
SpeechManage._d_read = (((omniORB.tcInternal.tv_string,0), omniORB.typeMapping["IDL:Manage/StringList:1.0"]), (), None)

# SpeechManage object reference
class _objref_SpeechManage (CORBA.Object):
    _NP_RepositoryId = SpeechManage._NP_RepositoryId

    def __init__(self):
        CORBA.Object.__init__(self)

    def read(self, *args):
        return _omnipy.invoke(self, "read", _0_Manage.SpeechManage._d_read, args)

    __methods__ = ["read"] + CORBA.Object.__methods__

omniORB.registerObjref(SpeechManage._NP_RepositoryId, _objref_SpeechManage)
_0_Manage._objref_SpeechManage = _objref_SpeechManage
del SpeechManage, _objref_SpeechManage

# SpeechManage skeleton
__name__ = "Manage__POA"
class SpeechManage (PortableServer.Servant):
    _NP_RepositoryId = _0_Manage.SpeechManage._NP_RepositoryId


    _omni_op_d = {"read": _0_Manage.SpeechManage._d_read}

SpeechManage._omni_skeleton = SpeechManage
_0_Manage__POA.SpeechManage = SpeechManage
omniORB.registerSkeleton(SpeechManage._NP_RepositoryId, SpeechManage)
del SpeechManage
__name__ = "Manage"

#
# End of module "Manage"
#
__name__ = "SpeechManage_idl"

_exported_modules = ( "Manage", )

# The end.
