# DO NOT EDIT THIS FILE!
#
# Python module Manage generated by omniidl

import omniORB
omniORB.updateModule("Manage")

# ** 1. Stub files contributing to this module
import SpeechManage_idl

# ** 2. Sub-modules

# ** 3. End
